module_name: Block Wishlist
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - wishlist
  - wish list
  - product registry
  - blockwishlist
description_short: The block wishlist adds a wishlist functionality to your site
description: description.md
images:
  - image-1.png
license: AFL